# Generated by Django 3.0.7 on 2021-10-01 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_appointment', models.DateField()),
                ('fname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('samithi', models.CharField(max_length=50)),
                ('bvguru', models.CharField(max_length=50)),
                ('sai_connect_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('gradual_decrease_in_vision', models.CharField(max_length=50, null=True)),
                ('sudden_decrease_in_vision', models.CharField(max_length=50, null=True)),
                ('blurred_distant_vision', models.CharField(max_length=50, null=True)),
                ('blurred_near_vision', models.CharField(max_length=50, null=True)),
                ('pain', models.CharField(max_length=50, null=True)),
                ('redness', models.CharField(max_length=50, null=True)),
                ('others', models.TextField(max_length=250, null=True)),
                ('past_history', models.CharField(max_length=50, null=True)),
                ('family_history', models.CharField(max_length=50, null=True)),
                ('Others2', models.TextField(max_length=250, null=True)),
                ('systemic_disease', models.CharField(max_length=100, null=True)),
                ('others3', models.TextField(max_length=250, null=True)),
                ('medication', models.CharField(max_length=50, null=True)),
                ('others4', models.TextField(max_length=250, null=True)),
                ('allergy', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
